---
language: node_js
node_js:
  - 10.8.0

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - node_modules
  
branches:
  only:
    - master
    - dev

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  #- yarn lint:hbs
  #- yarn lint:js
  - yarn test
  
notifications:
  email:
    on_failure: change
    on_success: change
